/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metodos;

/**
 *
 * @author igorr
 */
public class TelaCadastroAnimal extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroAnimal
     */
    public TelaCadastroAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomeAnimal = new javax.swing.JLabel();
        labelRacaAnimal = new javax.swing.JLabel();
        labelSexoAnimal = new javax.swing.JLabel();
        labelPesoAnimal = new javax.swing.JLabel();
        labelDataEntrada = new javax.swing.JLabel();
        labelFotoAnimal = new javax.swing.JLabel();
        labelCadastroAnimalTOP = new javax.swing.JLabel();
        botaoVoltarCadastroAnimal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNomeAnimal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNomeAnimal.setText("Nome:");

        labelRacaAnimal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelRacaAnimal.setText("Raça:");

        labelSexoAnimal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSexoAnimal.setText("Sexo:");

        labelPesoAnimal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPesoAnimal.setText("Peso:");

        labelDataEntrada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDataEntrada.setText("Data de entrada:");

        labelFotoAnimal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelFotoAnimal.setText("Foto:");

        labelCadastroAnimalTOP.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        labelCadastroAnimalTOP.setText("Cadastro do animal");

        botaoVoltarCadastroAnimal.setText("Voltar");
        botaoVoltarCadastroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarCadastroAnimalActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoreduzido.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoVoltarCadastroAnimal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFotoAnimal)
                            .addComponent(labelDataEntrada)
                            .addComponent(labelRacaAnimal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSexoAnimal)
                            .addComponent(labelPesoAnimal)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addComponent(labelCadastroAnimalTOP, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelNomeAnimal))
                        .addContainerGap(323, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastroAnimalTOP)
                .addGap(98, 98, 98)
                .addComponent(labelNomeAnimal)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRacaAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelSexoAnimal)
                        .addGap(18, 18, 18)
                        .addComponent(labelPesoAnimal)
                        .addGap(18, 18, 18)
                        .addComponent(labelDataEntrada)
                        .addGap(18, 18, 18)
                        .addComponent(labelFotoAnimal))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(botaoVoltarCadastroAnimal)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(900, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarCadastroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarCadastroAnimalActionPerformed
       TelaOpcoes tela3 = new TelaOpcoes();{
        tela3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoltarCadastroAnimalActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltarCadastroAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCadastroAnimalTOP;
    private javax.swing.JLabel labelDataEntrada;
    private javax.swing.JLabel labelFotoAnimal;
    private javax.swing.JLabel labelNomeAnimal;
    private javax.swing.JLabel labelPesoAnimal;
    private javax.swing.JLabel labelRacaAnimal;
    private javax.swing.JLabel labelSexoAnimal;
    // End of variables declaration//GEN-END:variables
}
